title: Lucas T. Page
description: A page to publish projects and informations
theme: just-the-docs

url: https://lucastrogo.github.io

aux_links:
  Template Repository: https://github.com/lucastrogo/lucastrogo.github.io


plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
