title: Lucas T. Page
description: A page to publish projects and informations
theme: just-the-docs

url: https://lucastrogo.github.io

aux_links:
  Template Repository: https://github.com/lucastrogo/lucastrogo.github.io


plugins:
  - jekyll-default-layout

color_scheme: dark